.TH GEXEC 1 "November  2, 2006"
.SH NAME
gexec \- Interactive run dialog
.SH SYNOPSIS
.B gexec
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B gexec
command.
.PP
\fBgexec\fP is a program that runs a small interactive command execution
dialog with history and autocompletition.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the README file.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-k, \-\-keepopen
Keep gExec open after executing a command.
.SH AUTHOR
gexec was written by Ferry Boender.
.PP
This manual page was written by Johann Rudloff <cypheon@gmx.net>,
for the Debian project (but may be used by others).
